# Generated by Django 6.0 on 2026-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_label_card_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='quick_facts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
