# Generated by Django 6.0 on 2026-01-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_keywords_card_quick_facts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
    ]
