# Generated by Django 6.0 on 2026-01-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_description'),
    ]

    operations = [
    ]
